[package]
name = "iced_gif"
version = "0.15.0-dev"
edition = "2021"
authors = ["tarkah <admin@tarkah.dev>"]
description = "A GIF widget for Iced"
license = "MIT"
repository = "https://github.com/tarkah/iced_gif"

[workspace]
default-members = [
  "./example"
]
members = [
  ".",
  "./example",
]

[features]
default = ["async-fs"]
tokio = ["dep:tokio"]

[dependencies]
iced = { version = "0.15.0-dev",  features = ["image"] }
iced_widget = "0.15.0-dev"
iced_futures = "0.15.0-dev"
iced_runtime = "0.15.0-dev"
thiserror = "1.0"

[dependencies.async-fs]
version = "1.6"
optional = true

[dependencies.tokio]
version = "1"
optional = true
features = ["fs", "io-util"]

[dependencies.image_rs]
package = "image"
version = "0.24"
features = ["gif"]

[patch.crates-io]
iced = { git = "https://github.com/squidowl/iced", rev = "de8164b9aed4f4bfa88c0458e4076a37be6496cc" }
iced_widget = { git = "https://github.com/squidowl/iced", rev = "de8164b9aed4f4bfa88c0458e4076a37be6496cc" }
iced_futures = { git = "https://github.com/squidowl/iced", rev = "de8164b9aed4f4bfa88c0458e4076a37be6496cc" }
iced_runtime = { git = "https://github.com/squidowl/iced", rev = "de8164b9aed4f4bfa88c0458e4076a37be6496cc" }
